### ISSUE TITLE
I want to change the audio format of the SIP communication to use only 0 and 8

### ISSUE THREAD

**Issue by cncodesy** [fonoster/routr#158] opened 2022-12-13 01:21 UTC
SDP：
INVITE sip:1002@192.168.1.212:5060 SIP/2.0
Via: SIP/2.0/WS gk9j02aa2cls.invalid;branch=z9hG4bK7674726
Max-Forwards: 69
To: <sip:1002@192.168.1.212:5060>
From: <sip:1001@192.168.1.212:5060>;tag=t6ps52n87c
Call-ID: hit5o1o3ldke0hsc7hgt
CSeq: 1071 INVITE
Contact: <sip:ghgf55mu@gk9j02aa2cls.invalid;transport=ws;ob>
Content-Type: application/sdp
Allow: INVITE,ACK,CANCEL,BYE,UPDATE,MESSAGE,OPTIONS,REFER,INFO,NOTIFY
Supported: ice,replaces,outbound
User-Agent: JsSIP 3.10.0
Content-Length: 2581

v=0
o=- 1336057480277847671 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=extmap-allow-mixed
a=msid-semantic: WMS F7d72YD7TLSs1Keyks68pjofGezlxjbLo49E
m=audio 61931 UDP/TLS/RTP/SAVPF 111 63 103 104 9 0 8 106 105 13 110 112 113 126

I want to change the audio format of the SIP communication to use only 0 and 8

**Comment by psanders** [comment] 2022-12-15 17:43
Hi @cncodes 👋

This is not possible with Routr (v1). 

In v2 (still alpha) you will be able to do this by creating a middleware.

Since this is not a bug, I'm closing this ticket. 

If you want to continue the conversation please go to [Fonoster/Discussions](https://github.com/fonoster/fonoster/discussions).

**Closed by psanders** 2022-12-15 17:43 UTC

**Comment by CNCodes** [comment] 2022-12-15 19:01
Hi there, just wanted to say I am NOT a collaborator on this project. I think this is for @cncodesy

**Comment by psanders** [comment] 2022-12-15 19:06
> Hi there, just wanted to say I am NOT a collaborator on this project. I think this is for @cncodesy

Ups sorry about that.
