### ISSUE TITLE
edgeport

### ISSUE THREAD

**Issue by happytulubi** [fonoster/routr#265] opened 2024-03-19 02:18 UTC
I followed the source code installation method and successfully installed it, but when starting edgeport, this error will be reported. What is the reason for this?

“Launcher.java unable to run edgeport: The Peer SIP Stack: gov.nist.javax.sip.SipStackImpl could not be instantiated. Ensure the Path Name has been set”

**Comment by psanders** [comment] 2024-03-19 15:39
You probably missing the keyStore and Truststore in your `edgeport.yaml`.

I can think of two options to solve this:

1. Remove the `securityContext` from the `edgeport.yaml` while you are developing. 
2. Check the installation steps in [gitpod config](https://github.com/fonoster/routr/blob/main/.gitpod.yml)  and try to replicate (that should give an environment)


<img width="457" alt="Screenshot 2024-03-19 at 11 38 48 AM" src="https://github.com/fonoster/routr/assets/539774/759846ff-cb64-44bf-ba27-91a230d67949">
nment ready to go)

**Comment by happytulubi** [comment] 2024-03-20 02:16
Excuse me, how is Location Service associated with EdgePort or Dispatcher? I see that Dispatcher is configured in EdgePort configuration, but a certain processor is configured in Dispatcher configuration. Do you need to develop this processor yourself. How does Routr proxy freeswitch and configure it

**Comment by happytulubi** [comment] 2024-03-20 02:20
Excuse me, how is Location Service associated with EdgePort or Dispatcher? I see that Dispatcher is configured in EdgePort configuration, but a certain processor is configured in Dispatcher configuration. Do you need to develop this processor yourself. How does Routr proxy freeswitch and configure it

**Comment by psanders** [comment] 2024-03-20 12:05
I'm closing this as I believe it is not a bug; however, feel free to re-open if needed.

**Closed by psanders** 2024-03-20 12:05 UTC
