### ISSUE TITLE
Use routr for a close group

### ISSUE THREAD

**Issue by plague-doctor** [fonoster/routr#48] opened 2019-09-09 03:23 UTC
Guys, I am so happy I have found your project that I cannot express in words. :clap: 
I just need some hand-holding and maybe a help with config files, etc.
We have a close group of users (6 people) and we would like to be able to communicate using VoIP. We do not need conference calls or calls outside of the group. We have a mixture of VoIP devices ranges from SoftPhones (LinPhone, CSIPSimple) to Yealink VoIP devices.
I would like to host routr.io on my Docker server. 
Can you guys give me some suggestions on how to configure routr to cater to what we are looking for? What ports should I open on the firewall? Any help would be highly appreciated.

**Comment by psanders** [comment] 2019-09-09 11:21
For your specific use case, I recommend looking into the [docker/compose guide](https://routr.io/docs/guides/running-with-docker-or-compose) and [basic-setup guide](https://routr.io/docs/guides/basic-setup). Those two guides will help you run Routr in your local network using Docker.

The next challenge is making Routr available outside of your network. Since you are running the service behind a NAT you will need to tell Routr to [use your outside-facing IP](https://routr.io/docs/configuration/general/#configuring-the-server-behind-a-nat). Also, You can use port `5060` unless is blocked by your ISP.

Finally, I recommend looking into a service like [no-ip](https://www.noip.com/) to make your setup more user friendly.

**Comment by plague-doctor** [comment] 2019-09-11 05:06
Thank you very much for your prompt reply, @psanders. I have configured my setup according to your suggestions, but few problems came up:

My config files look like this:
```
--------------------------------------------------------------- config.yml 
apiVersion: v1beta1
spec:
  externAddr: 203.xxx.xxx.xxx
  localnets: [192.168.1.0/24,192.168.10.0/24]

  transport:
    - protocol: udp
      port: 5060
    - protocol: tcp
      port: 5060
    - protocol: tls
      port: 5061
```
```
--------------------------------------------------------------- domains.yml
- apiVersion: v1beta1
  kind: Domain
  metadata:
    name: My SIP Server
  spec:
    context:
      domainUri: sip.my-domain.net
```
```
--------------------------------------------------------------- gateways.yml
- apiVersion: v1beta1
  kind: Gateway
  metadata:
    name: SIP-PROVIDER
    ref: GW01
  spec:
    host: my-sip-provider.com
    transport: tls
    credentials:
      username: 'username'
      secret: password
```
```
--------------------------------------------------------------- numbers.yml
- apiVersion: v1beta1
  kind: Number
  metadata:
    gwRef: GW01
    geoInfo:
      city: My-City
      country: My-Country
      countryISOCode: My-Country-Code
  spec:
    location:
      telUrl: 'tel:0000000000'
      aorLink: 'sip:1001@sip.my-domain.net'
```
```
--------------------------------------------------------------- agents.yml
- apiVersion: v1beta1
  kind: Agent
  metadata:
    name: Yealink
  spec:
    credentials:
      username: '1000'
      secret: '12345'
    domains: [sip.my-domain.net]

- apiVersion: v1beta1
  kind: Agent
  metadata:
    name: Mobile
  spec:
    credentials:
      username: '1001'
      secret: '12345'
    domains: [sip.my-domain.net]
```
```
--------------------------------------------------------------- peers.yml
- apiVersion: v1beta1
  kind: Peer
  metadata:
    name: Asterisk PBX
  spec:
    credentials:
      username: ast
      secret: '1234'
```
```
--------------------------------------------------------------- users.yml
- apiVersion: v1beta1
  kind: User
  metadata:
    name: Admin
  spec:
    credentials:
      username: 'admin'
      secret: 'changeit'
```

Router configuration:
- Ports Forwarded from WAN to Docker server: 5060, 5061, 5062, 5063, 4567 (TCP and UDP)

### Case 1: Using `1.0.0-rc3` release:
- Both my devices can successfully register with routr server (over TCP or TLS. UDP doesn't work). 
- When trying to call, I get this error:
`
[ERROR] TypeError: v.includes is not a function
`

### Case 2: Using previous `1.0.0-rc2` release:
- Both my devices can successfully register with routr server (over TCP or TLS. UDP doesn't work).
  - When both devices are in LAN (either 192.168.1.0/24 or 192.168.10.0/24) the connection is established and VoIP works fine. :+1:
  - When mobile uses `Mobile Network` I still can register with routr server, but I cannot establish any calls:
    - calling from Yealink (LAN) to outside: Mobile rings, cannot hear anything.
    - calling from Mobile (Outside) to Yealink (LAN):  No connection at all, error thrown:
`
[ERROR] javax.sip.TransactionUnavailableException: Could not resolve next hop or listening point unavailable!
`

#### Questions:
1. Please help with the configuration, so I can use external devices (mobiles, other group members devices).
2. Is there a problem with latest 1.0.0-rc3 release? `[ERROR] TypeError: v.includes is not a function` ?
3. In my use case I do not need to use any gateway. However I still need to provide files `gateways.yml`, `numbers.yml`... Routr fails without those files... Is there a way to ignore this requirement? 
4. I do not have any Asterisk PBX. Do I still need to provide `peers.yml` configuration? How to disable it?

**Comment by psanders** [comment] 2019-09-12 00:27
@plague-doctor 

I'm sorry you are having this many issues. I appreciate the detail report.

> Case 1: Using 1.0.0-rc3 release:
> Both my devices can successfully register with routr server (over TCP or TLS. UDP doesn't work).
> When trying to call, I get this error:
> [ERROR] TypeError: v.includes is not a function
> 

I successfully reproduced this issues and will work on fixing this in the next release. This `TypeError` seems to be related to the [default JS engine](https://github.com/fonoster/routr/issues/49). Try setting the environment variable `ROUTR_JS_ENGINE` to `graal.js` and let me know how it goes.

> 1. Please help with the configuration, so I can use external devices (mobiles, other group members devices).

Are you using a softphone on your mobile? If yes, which software are you using? I'm going to try to reproduce this issue tonight.

> 3. In my use case I do not need to use any gateway. However I still need to provide files gateways.yml, numbers.yml... Routr fails without those files... Is there a way to ignore this requirement?
> 4. I do not have any Asterisk PBX. Do I still need to provide peers.yml configuration? How to disable it?
> 

Unfortunately there is no way to disable this requirement. I can see how this is a pain, and will [remove the requirement](https://github.com/fonoster/routr/issues/50) in the next version

**Comment by psanders** [comment] 2019-09-15 13:00
The good news is that I was able to reproduce your situation. It appears to be a signaling issue due to the NAT. Allow me some time to think about a fix.

**Comment by jack-movember** [comment] 2019-09-26 02:56
I have noticed there is a new stable release. Good job @psanders :+1: 
Should this release fix issues I have got?

**Comment by psanders** [comment] 2019-09-27 11:12
Unfortunately thats not the case. I was installing a release workflow in the repo, and created a release by mistake. I'm still working in a solution for this issue.

**Comment by sosaucily** [comment] 2019-11-19 17:28
The issues getting SIP to work behind NATs seem quite substantial, at least it seems that way to me as many of the SIP servers I've tried in the past often have the issue of getting one SIP client to be able to forward RTP audio to the other when both are behind a NAT. If routr can find an easy way to configure this, that would be great. I've often seen other services use STUN or something similar to solve this.

**Comment by psanders** [comment] 2019-11-22 01:54
@sosaucily good point, NAT related issues are the worst. They consume most of my time with the project. It would be ideal to have something like rtpproxy as a plugging for Routr.

**Comment by sosaucily** [comment] 2019-11-23 15:30
👍 I also see Coturn STUN/TURN/ICE has a good community. Maybe an easy integration with that.

**Comment by psanders** [comment] 2020-05-31 13:08
After taking a more in-depth look at this issue, I noticed that this issue was a combination of your settings in Zoiper and potentially your Mobile network. After configuring my Zoiper using the [No audio or one-way audio](https://www.zoiper.com/en/support/answer/for/android/11/SIP_-_No_audio_or_one_way_audio) guide, I was able to get calling to work from Mobile-to-Wifi. 

However, to get Wifi-to-Mobile to work, I needed to use a VPN because my service provider blocks VoIP traffic. 

I'm closing this issue, but feel free to re-open if you still have problems.

**Closed by psanders** 2020-05-31 13:08 UTC
Labels: help-wanted, nat
